### ISSUE TITLE
Template - label:enhancement 

### ISSUE THREAD

**Issue by tborges** [elisiondesign/vue-code-highlight#16]
**Love your project `vue-code-highlight` ♥**

Currently, if I want to display just a single line of code I get this large block and doesn't look good.  
![image](https://user-images.githubusercontent.com/11985578/90317405-1551a680-dede-11ea-8f45-edd96abab147.png)

Is there a way of doing like this example below?
![image](https://user-images.githubusercontent.com/11985578/90317445-7a0d0100-dede-11ea-9362-a9b6c010b14b.png)

Thanks a lot

**Comment by honzabilek4** [comment]
Hello, 
thanks for the ❤️, we should a round of updates for this library, cause I see that it got quite neglected over the time. 
I tried to reproduce your issue and it seems that it's working for me. 
<img width="801" alt="Screenshot 2020-08-16 at 11 41 15" src="https://user-images.githubusercontent.com/7890555/90331559-b6f7f700-dfb5-11ea-843a-9c79b005cc47.png">
Are you sure you don't have some local styles being applied to the highlighted area?

**Comment by tborges** [comment]
No, I have not styles applied to the highlighted area.  

I'm using this package as **component**. 


But, I found out that if I have my component like this...
![image](https://user-images.githubusercontent.com/11985578/90335998-bba8b500-df8d-11ea-9c4b-f1c50c0dd673.png)
will generate my output like this...
![image](https://user-images.githubusercontent.com/11985578/90336008-d549fc80-df8d-11ea-893e-5a429e789dbd.png)  


  
### If my component is setup like this...
![image](https://user-images.githubusercontent.com/11985578/90336051-1c37f200-df8e-11ea-89a4-9997fe979b53.png)
will generate my output like this...
![image](https://user-images.githubusercontent.com/11985578/90336068-3376df80-df8e-11ea-9849-5206db5d96fe.png)


Well, I think this is good enough for me, unless you have another *TIP* for me.  
Thank you

**Comment by honzabilek4** [comment]
Well, this is completely different case then. 

The padding is caused by whitespace before and after the content. I think that preserving whitespace is a default behaviour of [vue-loader](https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler#options).
This can be changed to `condense`, but beware it affects the behaviour in the whole app. 

You can also experiment with [white-space](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) for the concrete element, but formatting your code as you suggested should do the trick. 🙂 

Let me know if you have any suggestions what to change or improve.
