### ISSUE TITLE
Other languages not working

### ISSUE THREAD

**Issue by elalienx** [elisiondesign/vue-code-highlight#3]
Hi, vue-code-highlight works really well with CSS, markup and JS languages. But I can't make it work for other languages like asm6502. How I add support for the rest of languages supported the Prism website?

**Comment by honzabilek4** [comment]
Hey, thanks for reaching out. 

We've originally extracted this component from our website to simplify the code structure a bit, together with a [prism-es6](https://github.com/elisiondesign/prism-es6) fork to enable for modern javascript features. 

This fork contains only the basic languages contained in the prism core though. This is  because we simply didn't need more we were counting on improving this in a future.

I'm willing to add this support for you and other folks now if you really wish to use this library.

Regards.

**Comment by elalienx** [comment]
Hi thanks for the quick support. I ended using CodeFlask because I want basic code editing features and it uses Prism.js as wells. That being said I was quite satisfied with the default functionality of vue-code-highlight

**Comment by honzabilek4** [comment]
It's fixed by https://github.com/elisiondesign/prism-es6/pull/3.
